### PR TITLE
Add support for unix sockets

### PR DESCRIPTION
**Pull request by Unkn0wn-MDCLXIV**
Added support for unix sockets.
Can be useful to setup a webserver as reverse-proxy to access pimatic.

### CODE REVIEW

**Comment by mwittig** [comment]
Thanks for your contribution! Do you have a working setup with a reverse proxy utilizing the unix socket feature? Are you happy to share this?

**Comment by Unkn0wn-MDCLXIV** [comment]
I have running lighttpd as a reverse-proxy. I can share the config of course.
I'm not conform with the syntax of apache/nginx, but it should be quite easy to configure as well.

Forcing a mode is not possible, if you create a server with an unix socket argument its in listen mode automatically.

You are right, I still have to add an unlink command on shutdown. Is the env.exit function in the startup.coffee the correct function to place this?
We should also check if the socket file still exists in case of an ungraceful shutdown.

**Comment by Unkn0wn-MDCLXIV** [comment]
My code now check on startup if the file already exists and removes it on exit.

**Comment by mwittig** [comment]
Excellent! Thanks for your contribution

**Pull request merged**
