### PR TITLE
Added DummyTemperatureSensor

### PR DESCRIPTION
**Pull request by michbeck100**
I've added a DummyTemperatureSensor. I needed this to test some code in pimatic-hap plugin and thought i shouldn't be the only one to benefit from these changes ;-).
The sensor is updated every 10 secs to some random value. It also supports humidity. 
It seems that my commit also added a lot of line feed changes (CR+LF to LF). There's nothing about line feed in the [docs](http://pimatic.org/guide/development/environment/)...

### CODE REVIEW

**Comment by Icesory** [comment]
What is the difference to an variables device?
I think this can done exact the same.

**Comment by michbeck100** [comment]
But it's not a temperature sensor. As far as I know are the dummy devices for testing purposes. I needed the dummy sensor to test another plugin, that I'm developing.
It's not a problem if there's no need for these changes. Just reject the pull request. I don't mind.

**Comment by sweebee** [comment]
agree with michbeck. For the mobile frontend the variables device is no problem. but other apps/plugins won't recognize this as a temperature device. 

The dummy temp device should also support input from the pimatic api.

**Comment by mwittig** [comment]
@sweebee Which plugins are you referring to? I think apps/pugins should provide means to refer to an temperature variable. In the end it just a number and a unit.

I don't like the fact that the DummyTemperatureSensor contains humidity too. That's a multi sensor (we don't have this in pimatic yet) or a WeatherStation if you like.

**Comment by michbeck100** [comment]
@mwittig I'm not sure sure if i understand you correct, but the pimatic-hap plugin needs to recognize devices by checking their template string (for temperature sensors this is 'temperature'). Since pimatic-hap calls device functions it needs more then just the values in form of variables.

I've added the humidity because a lot of the implementations for temperature sensors (eg. HomeduinoRFTemperature from pimatic-homeduino) support humidity, too. And because i needed it to support it in pimatic-hap.

**Comment by mwittig** [comment]
@michbeck100 Well, I think I need to have a closer look at pimatic-hap then to better understand the needs and to potentially come up with some suggestions. 

> As far as I know are the dummy devices for testing purposes.

I don't think there are for testing, only. Some users have used them to integrate external services with pimatic (e.g. by calling an action on the device), see https://forum.pimatic.org/topic/1104/solved-how-to-set-the-state-of-a-contact-sensor for example. However, these things have evolved in the wild and may be go beyond what @sweetpi had in mind originally.

**Comment by Icesory** [comment]
Why did you test for the device template? 
You can test for the device attributes. And there you get exactly what for an device you have. The temperature device is based on the variables device. So there should no real difference between them.

**Comment by michbeck100** [comment]
@Icesory For me the template defines the type of device. I could also check all attributes and actions, and then decide which device i have, but this is more complicated. Maybe i will do this in the future.

I'm not sure what temperature device you are talking about, but i refer to the TemperatureSensor class in devices.coffee and this device just extends Sensor which again extends Device. And there is a big difference to the VariablesDevice: first of all, the function get- and setTemperature() is missing.
I think we are at cross purposes here.

**Comment by michbeck100** [comment]
I've added a config option for the time after the random values are reset. 

Regarding the humidity, are there more opinions?

**Comment by michbeck100** [comment]
Are there still features missing? Would be great if someone could merge this PR or decline if the changes aren't wanted.

**Comment by sweetpi** [comment]
@michbeck100 Big thanks for the Pull Request and a big sorry for the late response. I'm currently on holiday and can't fully test the additions. 

I like the idea of a Dummy Temperature Sensor. However I think it would be more usefull if the values would not be random. What do you think about removing the random part and adding a device action for setting temperature and humanity (see for example [action implementation](https://github.com/pimatic/pimatic/blob/master/lib/devices.coffee#L811-L813) and [action declaration](https://github.com/pimatic/pimatic/blob/master/lib/devices.coffee#L474-L477))? The values could then be update over the http api:

```
/device/dummyTS/setTemperature?temperature=30
```
I think this is usefull for both: testing and production (for example to update from a external script or ESP node).

**Comment by SLiX69** [comment]
Would love this Dummy Temperature Sensor version sweetpi described!

**Comment by michbeck100** [comment]
@sweetpi I'll see what i can do ;-)

**Comment by michbeck100** [comment]
Done...

**Comment by sweetpi** [comment]
Big thanks for the changes. Manually merged into development. Will be released soon.

**Comment by WaJoWi** [comment]
I can set the temperature with 'set temp of ...', but how can I set the humidity in a rule?

**Comment by mwittig** [comment]
There is no action to change the humidity, currently. If this is required you may want to raise a feature request at <https://forum.pimatic.org/category/14/feature-requests>.  Please provide short description of your usage scenario in case.

Note beyond, it is possible to change the humidity attribute using the REST-API

**Pull request closed without merging**
