### PR TITLE
Add battery attribute to ContactSensor

### PR DESCRIPTION
**Pull request by betz0r**
Done for pimatic-max contact sensor with battery info in protocol but not in pimatic itself.
see https://github.com/pimatic/pimatic-max/pull/9

### CODE REVIEW

**Comment by betz0r** [comment]
Sorry for commit flood, but works now as intended. See https://github.com/pimatic/pimatic-max/pull/9

**Comment by betz0r** [comment]
The attribute "battery" is now also shown in GUI without the possibility to hide this attribute in the device's config.
As i am not that firm with pimatic's code about the option to hide attributes, can anyone add this functionality in the source code?

**Comment by tehmilcho** [comment]
Can you do the same for the MaxWallThermostat? In the debug log is also the Batterystate but not as Pimatic-attribute.

**Comment by mwittig** [comment]
I am closing this now as it does not fit with current design of generic devices in pimatic. I have augemented  your [PR ](https://github.com/pimatic/pimatic-max/pull/9)for pimatic-max to the missing features to `MaxContactSensor`.

Thanks

**Pull request closed without merging**
