### PR TITLE
Implementing ActionProvider for DummyPresenceSensor

### PR DESCRIPTION
**Pull request by Oitzu**

### CODE REVIEW

**Comment by Oitzu** [comment]
...for DummyPresenceSensor. Syntax: set presence of <device> present|absent

**Comment by sweebee** [comment]
Nice, maybe you can add it Also for the contact dummy?

**Comment by sweetpi** [comment]
Looks very good, thanks!

**Comment by sweebee** [comment]
How does it work for contacts? This doesnt work: set contact thuis to opened

**Comment by Oitzu** [comment]
"open|close (Device)"

**Pull request merged**
