### PR TITLE
issue 696: validate correctness of config against schema

### PR DESCRIPTION
**Pull request by tong67**
Made checkConfig(Entry) local, taken from declapi to be able to extend it with additional check between device schemas and config file. checkConfig from declapi still used by framework.coffee.
Added checkConfigAgainstSchema and search that perform the actual verification.
In checkConfigEntry added default and check on type. Some schema have format instead of type.
Found issue are printed as warnings and application continues (backward compatibility).

This is my fist experience with javascript/node.js/coffee so I hope the construction I used are not too bad (normally I do low level C stuff). Also first time I use git(hub) so hope I followed the right flow

### CODE REVIEW

**Comment by Icesory** [comment]
i dont see the problem with the declapi check.
Can you explain the purpose that you need an extended check?

**Comment by mwittig** [comment]
@Icesory See https://github.com/pimatic/pimatic/issues/696

**Comment by Icesory** [comment]
ah thanks @mwittig for the hint. this is off course a problem. In homeduino/rfcontroljs we do always a check but it throws no error. I will look into this.

**Comment by Icesory** [comment]
here is the fix for homeduino.
https://github.com/pimatic/pimatic-homeduino/commit/01efdcec9aca0894dc31b251dc1bcb65000e1cb6
i will wait for @sweetpi opinion to this and after this it will be merged into the master

**Comment by tong67** [comment]
I have created a wrong config.json with errors in wheater and rfswtich:
  "devices": [
    {
      "id": "weather",
      "class": "OpenWeatherDevice",
      "name": "Wheater",
      "location": "somewhere",
      "units": "metric",
      "lpng": "pl",
      "timeout": 3600000
    },
    {
      "id": "rfswitch6",
      "name": "RFSwitch6",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch6",
          "options": {
            "systemcide": 31,
            "programcode": 2
          }
        }
      ]
    }

The provided code change now reports them. Previous the non existing fields (lpng and systemcide) were ignored.
Normally this is not a problem. Except when an unwanted typo was introduced (in my case an unwanted space after systemcode).
It took me several days to figure out why the rf setup did not work as suppost to.
Log file now shows:
13:03:16.645 [pimatic] warn: No field 'type' defined for location. Update/correct schema?
13:03:16.662 [pimatic] warn: No field 'type' defined for units. Update/correct schema?
13:03:16.667 [pimatic] warn: No field 'type' defined for timeout. Update/correct schema?
13:03:16.681 [pimatic] warn: Device configuration of weather: Unknown config entry with name 'lpng'.
13:03:17.076 [pimatic] warn: Device configuration of rfswitch6: Unknown config entry with name 'systemcide'.

I still think this is a usefull check extension.

**Comment by Icesory** [comment]
I think your check dose not check against the used protocol. Replace switch6 with switch1 and correct the spelling error. Provide your code than a error? I think not,. 
But generally your improvement is good.

**Comment by tong67** [comment]
Change switch6 into switch1 and correct systemcode gives not error anymore.
I think you meant to change the name at level of class from RFSwitch6 into RFSwitch1 and correct systemcode.
When I did this, also no error was reported. This should not be the case (systemcode is not part of the protocolInfo of RFSwitch1).
When I change systemcode back to systemcide and leave RFSwitch1 an error is reported:
16:25:14.753 [pimatic] warn: Device configuration of rfswitch6: Unknown config entry with name 'systemcide'.

So the code does find a non existing name for the class (HomeduinoRFSwitch) but does not discriminate on name.

The code can be improved to signal these protocol mismatches as well.
I do not know whether that should be solved generic or within homeduino itself.

Current code does find typo's so still valid improvement (as stated by Icesory as well).

**Comment by Icesory** [comment]
No you are not 100% correct. Your "name" :"RFSwitch1" is the name of the device and has nothing to do with the protocol. 
The problem is that different protocols contains different properties. 
Your check looks only into the device-config-schema. And in this are all possible properties noticed. So your check checks for spelling errors which is great but it don't verified the protocol against the config. 

Take this device. It is definitely wrong! 
```
{
  "id": "rfswitch6",
  "name": "RFSwitch6",
  "class": "HomeduinoRFSwitch",
  "protocols": [
  {
    "name": "switch1",
    "options": {
      "systemcode": 31,
      "programcode": 2
    }
  }]
}
```
The protocol switch1 contains not the fields" systemcode" and "programcode" instead it uses "id" and "unit". 

Some time ago I voted to equalize all protocol fields but a higher force rejected it ;-) 

And now merry Christmas!

**Comment by leader21** [comment]
May the force be with you ;)
Merry Christmas to all of you too!

**Comment by tong67** [comment]
@Icesory you are correct, I mixed the protocol name and device presentation name in my answer. Due to the protocol fields differences base on the name, it is hard to create a generic check for this. More for homeduino to do the protocol field validation.

So what remains is check on spelling errors which can help during debugging non working setups

**Comment by sweetpi** [comment]
@tong67 Thank you for the pull request. I had no time to have a deeper look and do some testing. I will improve config validation in mid February and then take a close look at the pull request.

**Comment by sweetpi** [comment]
@tong67 I did remove the decl-api call completely and did set "additionalProperties" in the config schemes to *false*. The JSON scheme validation (using JaySchema) now works like expected and reports wrong spelled properties and we have less code :)

I'm very thankful for your implementation effort and pointing out the issue, but I think it is better to be handled by JaySchema. The additions will be released with the next master update.

**Pull request closed without merging**
