### PR TITLE
#863 set grunt-bump to fixed version.

### PR DESCRIPTION
**Pull request by michbeck100**

### CODE REVIEW

**Comment by mwittig** [comment]
Thanks!

**Comment by michbeck100** [comment]
The lint error fixes from 421dff7 should be applied to all other failing branches, too. ASAP

**Comment by mwittig** [comment]
@sweetpi Do you want me to fix this on master, developement, and knex0.9?

**Comment by mwittig** [comment]
Updated master and rebased development, removed knex0.9

**Pull request merged**
