### PR TITLE
Added DummyPresenceSensor (without autoReset function)

### PR DESCRIPTION
**Pull request by georg90**
To really make use of this it need to have "autoReset" implemented. How can this be done? I tried to extend the DummySensor with the Timer class..but without success..may @sweetpi you can add it?

### CODE REVIEW

**Comment by sweebee** [comment]
Test something like this:
```
resetPresence = ( =>
        @_setPresence(no)
      )
class DummyPresenceSensor extends PresenceSensor

    actions:
      changePresenceTo:
        params: 
          presence: 
            type: "boolean"

    constructor: (@config, lastState) ->
      @name = config.name
      @id = config.id
      @_contact = lastState?.presence?.value or off
      super()
        
    changePresenceTo: (presence) ->
      @_setPresence(presence)
      return Promise.resolve()

    if @config.autoReset is true
              @_resetPresenceTimeout = setTimeout(resetPresence, @config.resetTime)
```

config:
```
autoReset:
        description: """Reset the state after resetTime. Usefull for pir sensors, 
                      that emit present and absent events"""
        type: "boolean"
        default: true
      resetTime:
        description: "Time after that the presence value is reseted to absent."
        type: "integer"
        default: 10000
```

**Comment by sweetpi** [comment]
@sweebee Looks almost good. Buf we have additional to cancel the timeout in the case, the state changes back before the timeout occurs. I will add it.

**Comment by sweetpi** [comment]
@georg90 Big thanks for the addition.

**Comment by georg90** [comment]
@sweetpi that was fast :) thank you!

**Pull request merged**
