### PR TITLE
Make sure the in memory database is shared across multiple connections

### PR DESCRIPTION
**Pull request by joshendriks**
This will resolve issue #1073

### CODE REVIEW

**Comment by joshendriks** [comment]
@mwittig Would be great if this becomes part of the next release.  :)

**Comment by mwittig** [comment]
I am happy do this, however, your change appears to break the CI build. 
Can you please look into this? This will be great!

Looking at the build output you can basically ignore  error messages including except for the last one as all other messages are also on the master build log and don't cause the build to fail. 

```
19:41:55.940 [pimatic] Startup error: Error: PRAGMA synchronous=NORMAL; - SQLITE_BUSY: database is locked
19:41:55.940 [pimatic]>  at Error (native)
19:41:55.940 [pimatic]>
npm ERR! Test failed.  See above for more details.

**Comment by joshendriks** [comment]
I made sure the test now run in their own private cache.

**Comment by mwittig** [comment]
Honestly, I don't understand why you need to set "filename" to "file::memory:?cache=shared" as part of the test database configuration. Shouldn't your patch in Database::init take care of this? As far as I can see there is no code overlaying the init function. Can you please clarify?

**Comment by joshendriks** [comment]
The test database config set set to **private**, not **shared**. I had to do this to prevent the database instance getting shared between lib-database-test.coffee and pimatic-test.coffee.

**Comment by mwittig** [comment]
Thanks, got it ... 'private' instead of 'shared'

**Pull request merged**
